version: "3.3"
services:
  DS:
    image: timurs55/yapack:0.1
    ports:
      - "8001:8001"
    restart: always

  backend:
    image: dtankhaev/image_backend_ypacker:v1.00.00
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - DS
